"use client";

import React from "react";

// ─── Brand Tokens ──────────────────────────────────────────────────────────────
const C = {
  coral: "#e56859",
  coralDark: "#b05954",
  white: "#fcfcfc",
  charcoal: "#453c49",
  bg: "#0c0b0e",
  surface: "#13111a",
  surfaceHigh: "#1c1924",
  border: "#2a2433",
  borderHigh: "#3a3044",
  muted: "#7a6f85",
};

export default function FuturaTiersPage() {
  const calendarUrl =
    "https://link.futuradigital.app/widget/booking/SuJF7zuSUQtysLGaeDUL";
  const logoPath = "/futura-logo.png";

  const tiers = [
    {
      name: "Tier 1",
      title: "Lead Capture System",
      price: "From £47/mo",
      tagline: "Capture every enquiry generated by your ads.",
      partnerAngle:
        "Ideal for Google Ads partners who want to make sure no paid lead is lost or buried.",
      paidAdsLink:
        "Google Ads drives clicks and enquiries. This tier makes sure every form submission lands in the CRM, is organised in a pipeline, and triggers an instant notification to the business.",
      features: [
        "Lead capture forms",
        "CRM pipeline",
        "Lead notifications",
        "Conversations inbox",
        "Mobile app access",
      ],
      outcome: "Capture and organise leads from paid ads.",
      cta: "Discuss Tier 1",
      highlight: false,
    },
    {
      name: "Tier 2",
      title: "Lead Conversion System",
      price: "From £97/mo",
      tagline:
        "Respond faster and convert more of the leads you already pay for.",
      partnerAngle:
        "Best fit for Google Ads partners focused on improving lead-to-booking performance without adding operational complexity.",
      paidAdsLink:
        "When an ad lead comes in, the system responds quickly with SMS, missed-call text-back, booking options, and a direct WhatsApp button. That means faster response times and a better return on ad spend.",
      features: [
        "Everything in Tier 1",
        "SMS automation",
        "Missed call text-back",
        "Booking calendar",
        "WhatsApp button (direct to business)",
        "Mobile app access",
      ],
      outcome: "Turn ad enquiries into conversations and bookings.",
      cta: "Discuss Tier 2",
      highlight: true,
    },
    {
      name: "Tier 3",
      title: "AI Growth Engine",
      price: "From £197/mo",
      tagline: "Automate conversations, follow-up, and marketing with AI.",
      partnerAngle:
        "Designed for Google Ads partners who want to offer a complete growth system and improve retention with stronger downstream performance.",
      paidAdsLink:
        "Paid ads bring in the lead, and this tier handles the rest: CRM WhatsApp, AI receptionist, AI website chat, review generation, newsletters, campaigns, and reactivation. It turns paid traffic into a full growth engine.",
      features: [
        "Everything in Tier 2",
        "CRM WhatsApp integration",
        "AI Receptionist",
        "AI Chat Widget (full-time SDR)",
        "Marketing campaigns",
        "Newsletter campaigns",
        "Social media planner",
        "Reputation management",
        "Database reactivation",
        "Document management",
        "Mobile app access",
      ],
      outcome: "Turn paid leads into a fully automated customer journey.",
      cta: "Discuss Tier 3",
      highlight: false,
    },
  ];

  const comparisonRows = [
    ["Lead capture forms", true, true, true],
    ["CRM pipeline", true, true, true],
    ["Lead notifications", true, true, true],
    ["Mobile app access", true, true, true],
    ["SMS automation", false, true, true],
    ["Missed call text-back", false, true, true],
    ["Booking calendar", false, true, true],
    ["WhatsApp button (direct chat)", false, true, true],
    ["CRM WhatsApp integration", false, false, true],
    ["Marketing campaigns", false, false, true],
    ["Newsletter campaigns", false, false, true],
    ["Social media planner", false, false, true],
    ["Reputation management", false, false, true],
    ["Database reactivation", false, false, true],
    ["Document management", false, false, true],
    ["AI Receptionist", false, false, true],
    ["AI Chat Widget (SDR)", false, false, true],
  ] as const;

  return (
    <div
      className="min-h-screen"
      style={{ backgroundColor: C.bg, color: C.white }}
    >
      {/* ── Hero ─────────────────────────────────────────────────────────────── */}
      <section
        style={{
          borderBottom: `1px solid ${C.border}`,
          background: `radial-gradient(circle at top left, rgba(229,104,89,0.08), transparent 35%), ${C.bg}`,
        }}
      >
        <div className="mx-auto max-w-7xl px-6 py-20 md:px-10 lg:px-12">
          <div className="max-w-5xl">
            <div className="mb-10 flex items-center gap-4">
              <img src={logoPath} alt="Futura Digital" className="h-10 w-auto" />
              <div>
                <p
                  className="text-sm font-semibold tracking-wide"
                  style={{ color: C.white }}
                >
                  Futura Digital
                </p>
                <p className="text-sm" style={{ color: C.muted }}>
                  Ads conversion infrastructure for service businesses
                </p>
              </div>
            </div>

            <span
              className="inline-flex rounded-full px-4 py-1 text-sm font-medium"
              style={{
                border: `1px solid ${C.border}`,
                color: C.coral,
                backgroundColor: C.surface,
              }}
            >
              Google Ads Partner Offer
            </span>

            <h1
              className="mt-6 max-w-4xl text-4xl font-semibold tracking-tight md:text-6xl"
              style={{ color: C.white, lineHeight: 1.05 }}
            >
              The CRM system that helps Google Ads clients convert more of the
              leads they already pay for.
            </h1>

            <p
              className="mt-6 max-w-3xl text-lg leading-8 md:text-xl"
              style={{ color: C.muted }}
            >
              You run the ads. We install the system that captures, responds to,
              and converts enquiries faster — helping your clients see better
              ROI and helping you retain accounts with more confidence.
            </p>

            <div className="mt-10 flex flex-wrap gap-4">
              <a
                href={calendarUrl}
                target="_blank"
                rel="noreferrer"
                className="rounded-2xl px-6 py-3 text-sm font-medium shadow-sm transition hover:opacity-90"
                style={{ backgroundColor: C.coral, color: C.white }}
              >
                Book a partner call
              </a>

              <a
                href="#comparison"
                className="rounded-2xl px-6 py-3 text-sm font-medium transition"
                style={{
                  border: `1px solid ${C.border}`,
                  color: C.white,
                  backgroundColor: "transparent",
                }}
                onMouseEnter={(e) =>
                  (e.currentTarget.style.backgroundColor = C.surface)
                }
                onMouseLeave={(e) =>
                  (e.currentTarget.style.backgroundColor = "transparent")
                }
              >
                Compare features
              </a>
            </div>

            <div className="mt-10 grid gap-3 md:grid-cols-3">
              {[
                "Capture every paid lead",
                "Improve response speed and booking rate",
                "Upgrade into AI, WhatsApp and automation",
              ].map((item) => (
                <div
                  key={item}
                  className="rounded-2xl px-4 py-4 text-sm"
                  style={{
                    backgroundColor: C.surface,
                    border: `1px solid ${C.border}`,
                    color: C.muted,
                  }}
                >
                  <span
                    className="mr-3 inline-block h-2.5 w-2.5 rounded-full"
                    style={{ backgroundColor: C.coral }}
                  />
                  {item}
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Capture / Convert / Grow ─────────────────────────────────────────── */}
      <section className="mx-auto max-w-7xl px-6 py-16 md:px-10 lg:px-12">
        <div className="grid gap-6 md:grid-cols-3">
          {[
            {
              step: "Step 1",
              title: "Capture",
              body: "Every enquiry from Google Ads, landing pages, or the website is captured and organised.",
            },
            {
              step: "Step 2",
              title: "Convert",
              body: "Faster responses, SMS follow-up, missed call text-back, and booking tools improve lead conversion.",
            },
            {
              step: "Step 3",
              title: "Grow",
              body: "AI, WhatsApp, reviews, campaigns, and reactivation turn ad leads into a long-term growth engine.",
            },
          ].map((card) => (
            <div
              key={card.title}
              className="rounded-3xl p-8 shadow-sm"
              style={{
                border: `1px solid ${C.border}`,
                backgroundColor: C.surface,
              }}
            >
              <p className="text-sm font-medium" style={{ color: C.coral }}>
                {card.step}
              </p>
              <h3
                className="mt-3 text-2xl font-semibold"
                style={{ color: C.white }}
              >
                {card.title}
              </h3>
              <p className="mt-3 leading-7" style={{ color: C.muted }}>
                {card.body}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Tiers ────────────────────────────────────────────────────────────── */}
      <section
        id="tiers"
        className="mx-auto max-w-7xl px-6 pb-20 md:px-10 lg:px-12"
      >
        <div className="mb-10 max-w-3xl">
          <h2
            className="text-3xl font-semibold tracking-tight md:text-4xl"
            style={{ color: C.white }}
          >
            The three tiers
          </h2>
          <p className="mt-4 text-lg leading-8" style={{ color: C.muted }}>
            Each package is designed to support a different stage of the
            customer journey, while giving the Google Ads partner a stronger
            performance story.
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-3">
          {tiers.map((tier) => {
            const isHighlight = tier.highlight;
            const cardBg = isHighlight ? C.surfaceHigh : C.surface;
            const cardBorder = isHighlight ? C.coral : C.border;
            const textPrimary = C.white;
            const textSecondary = isHighlight ? "#d4cfe0" : C.muted;
            const innerBg = isHighlight ? "rgba(229,104,89,0.1)" : C.bg;
            const labelColor = isHighlight ? C.coral : C.muted;

            return (
              <div
                key={tier.name}
                className="relative flex h-full flex-col rounded-3xl p-8 shadow-sm"
                style={{
                  border: `1px solid ${cardBorder}`,
                  backgroundColor: cardBg,
                }}
              >
                {isHighlight && (
                  <div
                    className="absolute -top-3 left-8 rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-wide"
                    style={{ backgroundColor: C.coral, color: C.white }}
                  >
                    Most popular
                  </div>
                )}

                <div className="flex items-start justify-between gap-4">
                  <div>
                    <p className="text-sm font-medium" style={{ color: labelColor }}>
                      {tier.name}
                    </p>
                    <h3
                      className="mt-2 text-2xl font-semibold"
                      style={{ color: textPrimary }}
                    >
                      {tier.title}
                    </h3>
                  </div>
                  <div
                    className="rounded-2xl px-3 py-2 text-sm font-medium"
                    style={{
                      backgroundColor: innerBg,
                      color: isHighlight ? C.coral : C.muted,
                      border: `1px solid ${C.border}`,
                    }}
                  >
                    {tier.price}
                  </div>
                </div>

                <p className="mt-5 text-base leading-7" style={{ color: textSecondary }}>
                  {tier.tagline}
                </p>

                <div className="mt-6 rounded-2xl p-4" style={{ backgroundColor: innerBg }}>
                  <p
                    className="text-xs font-semibold uppercase tracking-wide"
                    style={{ color: labelColor }}
                  >
                    Google Ads partner angle
                  </p>
                  <p className="mt-2 text-sm leading-6" style={{ color: textSecondary }}>
                    {tier.partnerAngle}
                  </p>
                </div>

                <div className="mt-4 rounded-2xl p-4" style={{ backgroundColor: innerBg }}>
                  <p
                    className="text-xs font-semibold uppercase tracking-wide"
                    style={{ color: labelColor }}
                  >
                    How it links to paid ads
                  </p>
                  <p className="mt-2 text-sm leading-6" style={{ color: textSecondary }}>
                    {tier.paidAdsLink}
                  </p>
                </div>

                <ul className="mt-8 space-y-3">
                  {tier.features.map((feature) => (
                    <li key={feature} className="flex items-start gap-3 text-sm leading-6">
                      <span
                        className="mt-1 inline-block h-2.5 w-2.5 flex-shrink-0 rounded-full"
                        style={{ backgroundColor: C.coral }}
                      />
                      <span style={{ color: textSecondary }}>{feature}</span>
                    </li>
                  ))}
                </ul>

                <div className="mt-8 pt-6" style={{ borderTop: `1px solid ${C.border}` }}>
                  <p className="text-sm" style={{ color: C.muted }}>
                    Outcome
                  </p>
                  <p className="mt-2 text-base font-medium" style={{ color: textPrimary }}>
                    {tier.outcome}
                  </p>
                </div>

                <a
                  href={calendarUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="mt-8 inline-flex rounded-2xl px-5 py-3 text-sm font-medium transition hover:opacity-90"
                  style={
                    isHighlight
                      ? { backgroundColor: C.coral, color: C.white }
                      : {
                          backgroundColor: C.surfaceHigh,
                          color: C.white,
                          border: `1px solid ${C.border}`,
                        }
                  }
                >
                  {tier.cta}
                </a>
              </div>
            );
          })}
        </div>
      </section>

      {/* ── Comparison Table ─────────────────────────────────────────────────── */}
      <section
        id="comparison"
        style={{
          borderTop: `1px solid ${C.border}`,
          borderBottom: `1px solid ${C.border}`,
          backgroundColor: C.surface,
        }}
      >
        <div className="mx-auto max-w-7xl px-6 py-20 md:px-10 lg:px-12">
          <div className="mb-10 max-w-3xl">
            <h2
              className="text-3xl font-semibold tracking-tight md:text-4xl"
              style={{ color: C.white }}
            >
              Feature comparison
            </h2>
            <p className="mt-4 text-lg leading-8" style={{ color: C.muted }}>
              A simple view of what each tier includes, so partners can match
              the right system to the client's paid ads maturity.
            </p>
          </div>

          <div
            className="overflow-hidden rounded-3xl shadow-sm"
            style={{ border: `1px solid ${C.border}` }}
          >
            <div
              className="grid grid-cols-4 text-sm font-semibold"
              style={{
                backgroundColor: C.surfaceHigh,
                borderBottom: `1px solid ${C.border}`,
              }}
            >
              <div className="px-6 py-4" style={{ color: C.muted }}>
                Feature
              </div>
              {["Tier 1", "Tier 2", "Tier 3"].map((t) => (
                <div key={t} className="px-6 py-4 text-center" style={{ color: C.white }}>
                  {t}
                </div>
              ))}
            </div>

            {comparisonRows.map(([label, t1, t2, t3], index) => (
              <div
                key={String(label)}
                className="grid grid-cols-4 text-sm"
                style={{ backgroundColor: index % 2 === 0 ? C.bg : C.surface }}
              >
                <div className="px-6 py-4 font-medium" style={{ color: C.white }}>
                  {label}
                </div>
                {[t1, t2, t3].map((value, vi) => (
                  <div
                    key={`${label}-${vi}`}
                    className="flex items-center justify-center px-6 py-4"
                  >
                    <span
                      className="inline-flex h-8 w-8 items-center justify-center rounded-full text-sm font-semibold"
                      style={
                        value
                          ? { backgroundColor: C.coral, color: C.white }
                          : { backgroundColor: C.surfaceHigh, color: C.muted }
                      }
                    >
                      {value ? "✓" : "—"}
                    </span>
                  </div>
                ))}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Partner Pitch + Paid Ads Flow ────────────────────────────────────── */}
      <section className="mx-auto max-w-7xl px-6 py-20 md:px-10 lg:px-12">
        <div className="grid gap-6 lg:grid-cols-2">
          <div
            className="rounded-3xl p-8 shadow-sm"
            style={{ border: `1px solid ${C.border}`, backgroundColor: C.surface }}
          >
            <p
              className="text-sm font-semibold uppercase tracking-wide"
              style={{ color: C.coral }}
            >
              Partner pitch
            </p>
            <h3 className="mt-3 text-2xl font-semibold" style={{ color: C.white }}>
              The message to the Google Ads agency
            </h3>
            <p className="mt-4 leading-7" style={{ color: C.muted }}>
              We are not replacing the ads strategy. We are strengthening what
              happens after the click. The better the lead handling, the better
              the campaign performs, and the easier it is for the agency to
              retain the client.
            </p>
          </div>

          <div
            className="rounded-3xl p-8 shadow-sm"
            style={{ border: `1px solid ${C.border}`, backgroundColor: C.surface }}
          >
            <p
              className="text-sm font-semibold uppercase tracking-wide"
              style={{ color: C.coral }}
            >
              Paid ads flow
            </p>
            <h3 className="mt-3 text-2xl font-semibold" style={{ color: C.white }}>
              From click to customer
            </h3>
            <div className="mt-6 space-y-3 text-sm">
              {[
                "Google Ads drives traffic",
                "Landing page or website captures the enquiry",
                "CRM logs the lead and alerts the business",
                "SMS, booking, WhatsApp, or AI handles the response",
                "Reviews, campaigns, and reactivation grow long-term value",
              ].map((item) => (
                <div
                  key={item}
                  className="flex items-center gap-3 rounded-2xl px-4 py-3"
                  style={{ backgroundColor: C.bg, border: `1px solid ${C.border}` }}
                >
                  <span
                    className="inline-block h-2.5 w-2.5 flex-shrink-0 rounded-full"
                    style={{ backgroundColor: C.coral }}
                  />
                  <span style={{ color: C.muted }}>{item}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Footer CTA ───────────────────────────────────────────────────────── */}
      <section
        style={{
          borderTop: `1px solid ${C.border}`,
          background: `linear-gradient(180deg, ${C.surface} 0%, ${C.bg} 100%)`,
        }}
      >
        <div className="mx-auto max-w-7xl px-6 py-16 md:px-10 lg:px-12">
          <div
            className="flex flex-col items-start justify-between gap-6 rounded-3xl p-8 lg:flex-row lg:items-center"
            style={{
              border: `1px solid ${C.borderHigh}`,
              backgroundColor: C.surfaceHigh,
            }}
          >
            <div className="max-w-2xl">
              <p
                className="text-sm font-semibold uppercase tracking-wide"
                style={{ color: C.coral }}
              >
                Ready to talk?
              </p>
              <h3
                className="mt-3 text-2xl font-semibold md:text-3xl"
                style={{ color: C.white }}
              >
                Ready to add a conversion system to your Google Ads offer?
              </h3>
              <p className="mt-3 leading-7" style={{ color: C.muted }}>
                Book a call and see how Futura Digital can help your clients
                capture, respond to, and convert more enquiries.
              </p>
            </div>

            <a
              href={calendarUrl}
              target="_blank"
              rel="noreferrer"
              className="rounded-2xl px-6 py-3 text-sm font-medium transition hover:opacity-90"
              style={{ backgroundColor: C.coral, color: C.white }}
            >
              Book a partner call
            </a>
          </div>
        </div>
      </section>
    </div>
  );
}